
### Here is my resume:

Sophia Miller
659 West 162nd St., Apartment 34, New York, NY 10032
845-332-5516
sm4594@cumc.columbia.edu

EDUCATION

Columbia University Mailman School of Public Health			          	          New York, NY
MPH Candidate, May 2020 
Department of Epidemiology, Certificate in Infectious Disease Epidemiology

Middlebury College								                    Middlebury, VT
Bachelor of Arts in Sociology/Anthropology, May 2016
Pre-medical track, minor in Global Health 
Honors: College Scholar (highest academic honor, four semesters), senior thesis honors


EXPERIENCE

ICAP at Columbia University Mailman School of Public Health		                      
Health Informatics Assistant, Strategic Information Unit 		                      New York, NY
September 2019 – Present
•	Programmed web-based questionnaires using SurveyCTO
•	Prepared Respondent Driven Sampling (RDS) recruitment diagnostics reports for integrated bio-behavioral surveys (IBBS) using RDS Analyst
•	Prepared tables, figures, and posters for various ICAP manuscripts and academic conferences
                        
Next Generation Intern, Strategic Information Unit		                           Harare, Zimbabwe
June 2019-August 2019
•	Assisted in the implementation of an integrated bio-behavioral survey (IBBS) among men who have sex with men and transgender womenin Harare and Bulawayo, Zimbabwe
•	Facilitated care referral follow-up for participants testing HIV positive
•	Facilitated data checks for questionnaire data, viral load results, and RDS coupon manager
•	Cleaned survey dataset in preparation for analysis
•	Collaborated with ICAP staff to draft a manuscript based on the results of the formative assessment for the IBBS
•	Prepared tables and figures for the IBBS data analysis and dissemination meeting

New York State Psychiatric Institute                                                                                New York, NY
Research Assistant, HIV Center for Clinical and Behavioral Studies	          
October 2018-May 2019
•	Developed an innovative peer-to-peer recruitment method for a National Institute of Mental Health funded pilot study to create a gender-enhanced PrEP information-motivation workshop for young South African women
•	Supported implementation and data analysis of several ongoing studies relating to PrEP access and uptake, both in the US and internationally
UCSF Global Strategic Information (GSI)                                                                   San Francisco, CA
Project Assistant, NAMPHIA              				    
July 2017- December 2017
•	Assisted in the operational and budget management of the Namibia Population-based HIV Impact Assessment (NAMPHIA) survey
•	Creating mobile data collection tools using Open Data Kit for an integrated bio- behavioral survey among men who have sex with men and female sex workers in Namibia and an anti-retroviral treatment outcomes study in Jamaica
•	Developed qualitative research methods for a study evaluating a pediatric HIV disclosure intervention in Uganda

UCSF Bioethics                                                                                                             San Francisco, CA
Program Associate
February 2017- June 2017
•	Served as research coordinator for an NIH-funded study investigating the ethical dimensions of a breast cancer prevention clinical trial, with contributions including data management, qualitative data analysis, literature reviews, and facilitation of team communication
•	Assisted in program development for the nascent USCF Bioethics program, including communications, website development, and management of the Director’s schedule

UCSF Malaria Elimination Initiative (MEI)                                                               San Francisco, CA
Research/Communications Intern
August 2016- January 2017
•	Drafted country briefs to communicate the progress and challenges faced by eliminating countries to key stakeholders
•	Played a lead role in drafting, designing, and launching items for the MEI’s Malaria Elimination Toolkit, with a focus on the Primaquine Monitoring Pharmacovigilance Tool, which provides healthcare providers and national malaria programs with a system to monitor the safety of single low-dose primaquine
•	Created impact and digital analytics reports to help improve the MEI’s communications activities

Weill Cornell Department of Healthcare Policy and Research                                       New York, NY
Research Intern
May 2015- August 2015
•	Designed and implemented qualitative research methods for a study looking at the barriers and facilitators to effective pediatric epilepsy care
•	Co-authored a published paper on the results of the pediatric epilepsy study


SKILLS AND CERTIFICATIONS

Advanced knowledge of MS Excel and SAS; Intermediate knowledge of Open Data Kit, SurveyCTO, R, RDS Analyst, and QGIS; CITI Human Subjects Protection and HIPAA Patient Privacy certified


PUBLICATIONS

Baria Hafeez, MS, Sophia Miller, Anup D. Patel, MD, Zachary M. Grinspan, MD, MS. Care Management at a Pediatric Accountable Care Organization (ACO): A Qualitative Analysis. 2017. Epilepsy and Behavior.


ADDITIONAL

NYC Department of Health and Mental Hygiene Team Epi Volunteer Outbreak Investigator (2018-present); Mentor at Middlebury College Community Friends Program (2014-2016); Middlebury College Women’s Varsity Crew Team (2012-2016)

