---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(viridis)
library(plotly)
```

```{r}
data("instacart")
instacart_data = instacart %>% 
  filter(aisle %in% c("frozen produce", "baking ingredients", "ice cream ice"))
```

Column {data-width=450}
-----------------------------------------------------------------------

### Number of Items Ordered from Selected Aisles

```{r}
instacart_data %>%
group_by(aisle) %>% 
  summarize(
    n_items_ordered = n()) %>% 
  mutate(
    aisle = reorder(aisle, n_items_ordered)) %>%  
  plot_ly(x = ~aisle, y = ~n_items_ordered, type = "bar", color = ~aisle) %>% 
  layout(
    xaxis = list(title = "Aisle"),
    yaxis = list(title = "Number of Items Ordered")
    )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Days Since Prior Order (capped at 30 days)

```{r}
instacart_data %>% 
  plot_ly(x = ~aisle, y = ~days_since_prior_order, type = "box", color = ~aisle) %>% 
 layout(
    xaxis = list(title = "Aisle"),
    yaxis = list(title = "Days Since Prior Order")
    )
```

### Number of Orders by Day of Week

```{r}
instacart_data %>%
  mutate(
    order_dow = as.factor(order_dow)) %>% 
  arrange(order_dow) %>% 
  mutate(
    day = recode(order_dow, '0' = "Sunday", '1' = "Monday", '2' = "Tuesday", '3' = "Wednesday", '4' = "Thursday", '5' = "Friday", '6' = "Saturday")) %>% 
  group_by(aisle, day) %>% 
  summarize(
    n = n()
  ) %>% 
  distinct(.keep_all = TRUE) %>% 
  plot_ly(x = ~day, y = ~n, type = "scatter", mode = "lines", color = ~aisle) %>% 
  layout(
    xaxis = list(title = "Day"),
    yaxis = list(title = "Items Ordered")
    )
```