---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("instacart")
instacart_data = instacart %>% 
  filter(aisle %in% c("frozen produce", "baking ingredients", "ice cream ice"))
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart_data %>%
group_by(aisle) %>% 
  summarize(
    n_items_ordered = n()) %>% 
  mutate(
    aisle = reorder(aisle, n_items_ordered)) %>% 
  plot_ly(x = ~aisle, y = ~n_items_ordered, type = "bar", color = "red") %>% 
  layout(
    title = "Number of Items Ordered from Selected Aisles",
    xaxis = list(title = "Aisle"),
    yaxis = list(title = "Number of Items Ordered")
    )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart_data %>%
  filter(aisle == "baking ingredients") %>% 
  mutate(
    order_dow = as.factor(order_dow)
    ) %>% 
  mutate(
    day = recode(order_dow, '0' = "Sunday", '1' = "Monday", '2' = "Tuesday", '3' = "Wednesday", '4' = "Thursday", '5' = "Friday", '6' = "Saturday")
    ) %>% 
  group_by(order_number, day) %>% 
  mutate(
    n = n()
    ) %>% 
  plot_ly(x = ~day, y = ~n, color = ~day, type = "box") %>% 
  layout(
    title = "Number of Baking Ingredients Ordered by Day of Week",
    xaxis = list(title = " "),
    yaxis = list(title = "Number of Items Ordered")
    )
```

### Chart C

```{r}
hour_density = instacart_data %>%
  ggplot(aes(x = order_hour_of_day, fill = aisle)) +
  geom_density(alpha = 0.5) +
  ggtitle("Order Time of Day by Aisle") +
  ylab("Density") +
  xlab("Hour of Day")

ggplotly(hour_density)
  
```

